# Generated by Django 5.2 on 2025-08-19 16:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("merchant", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CuisineType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_delete", models.BooleanField(default=False)),
                ("create_time", models.DateTimeField(auto_now_add=True)),
                ("update_time", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "country_of_origin",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text="Icon class or emoji",
                        max_length=50,
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Cuisine Type",
                "verbose_name_plural": "Cuisine Types",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="DietaryRestriction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_delete", models.BooleanField(default=False)),
                ("create_time", models.DateTimeField(auto_now_add=True)),
                ("update_time", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text="Icon class or emoji",
                        max_length=50,
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Dietary Restriction",
                "verbose_name_plural": "Dietary Restrictions",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="CustomerProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_delete", models.BooleanField(default=False)),
                ("create_time", models.DateTimeField(auto_now_add=True)),
                ("update_time", models.DateTimeField(auto_now=True)),
                ("is_vegetarian", models.BooleanField(default=False)),
                ("is_vegan", models.BooleanField(default=False)),
                ("is_gluten_free", models.BooleanField(default=False)),
                ("is_dairy_free", models.BooleanField(default=False)),
                (
                    "spice_tolerance",
                    models.CharField(
                        choices=[
                            ("mild", "Mild"),
                            ("medium", "Medium"),
                            ("hot", "Hot"),
                            ("extra_hot", "Extra Hot"),
                        ],
                        default="medium",
                        max_length=20,
                    ),
                ),
                (
                    "preferred_cuisines",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of preferred cuisine types",
                    ),
                ),
                (
                    "allergies",
                    models.JSONField(
                        blank=True, default=list, help_text="List of food allergies"
                    ),
                ),
                (
                    "preferred_areas",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of preferred areas for food search",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="customer_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Customer Profile",
                "verbose_name_plural": "Customer Profiles",
            },
        ),
        migrations.CreateModel(
            name="FoodRecommendation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_delete", models.BooleanField(default=False)),
                ("create_time", models.DateTimeField(auto_now_add=True)),
                ("update_time", models.DateTimeField(auto_now=True)),
                (
                    "confidence_score",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="AI confidence score (0-1)",
                        max_digits=3,
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        blank=True,
                        help_text="Why this item was recommended",
                        max_length=200,
                        null=True,
                    ),
                ),
                ("is_viewed", models.BooleanField(default=False)),
                ("is_clicked", models.BooleanField(default=False)),
                (
                    "menu_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommendations",
                        to="merchant.menuitem",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="food_recommendations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Food Recommendation",
                "verbose_name_plural": "Food Recommendations",
                "ordering": ["-confidence_score"],
                "unique_together": {("user", "menu_item")},
            },
        ),
        migrations.CreateModel(
            name="UserPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_delete", models.BooleanField(default=False)),
                ("create_time", models.DateTimeField(auto_now_add=True)),
                ("update_time", models.DateTimeField(auto_now=True)),
                (
                    "min_price",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "max_price",
                    models.DecimalField(
                        decimal_places=2, default=1000.0, max_digits=10
                    ),
                ),
                (
                    "max_distance",
                    models.PositiveIntegerField(
                        default=10, help_text="Maximum distance in kilometers"
                    ),
                ),
                (
                    "min_rating",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
                ),
                ("email_notifications", models.BooleanField(default=True)),
                ("push_notifications", models.BooleanField(default=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="food_preferences",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Preference",
                "verbose_name_plural": "User Preferences",
                "unique_together": {("user",)},
            },
        ),
    ]
