# Generated by Django 5.2 on 2025-08-19 12:07

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(max_length=100, unique=True)),
                ('value', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='applicationuser',
            name='device_id',
        ),
        migrations.RemoveField(
            model_name='applicationuser',
            name='device_name',
        ),
        migrations.RemoveField(
            model_name='applicationuser',
            name='ip_address',
        ),
        migrations.RemoveField(
            model_name='applicationuser',
            name='os_version',
        ),
        migrations.AddField(
            model_name='applicationuser',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='Address'),
        ),
        migrations.AddField(
            model_name='applicationuser',
            name='area',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Area'),
        ),
        migrations.AddField(
            model_name='applicationuser',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='applicationuser',
            name='is_merchant',
            field=models.BooleanField(default=False, help_text='Designates whether the user is a merchant.', verbose_name='Is Merchant'),
        ),
        migrations.AddField(
            model_name='applicationuser',
            name='merchant_id',
            field=models.PositiveIntegerField(blank=True, help_text='Stores related MerchantProfile ID.', null=True, verbose_name='Merchant ID'),
        ),
        migrations.AddField(
            model_name='applicationuser',
            name='pin',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='PIN Code'),
        ),
        migrations.AddField(
            model_name='applicationuser',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='applicationuser',
            name='username',
            field=models.CharField(blank=True, default='', error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Lettres , digits and @/./+/-/ only .', max_length=150, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username'),
        ),
    ]
